# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# using a non-local repo creates a venv for the pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-added-large-files
        exclude: assets
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.8.3"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^tests
      - id: ruff-format
        exclude: ^tests
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args:
          [
            --contrib=CT1,
            --ignore=title-trailing-punctuation,
            --ignore=T3,
            --ignore=B6,
            --msg-filename,
          ]
