apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-
  labels: {}
  namespace: enterprise-mlops
spec:
  activeDeadlineSeconds: 86400
  arguments:
    parameters:
      - name: param1
        value: 41
      - name: param2
        value: hello world
      - name: integer
        value: 1
      - name: floater
        value: 3.14
      - name: stringer
        value: hello
      - name: run_id
        value: PLEASE_SET_RUN_ID
      - name: retry_run_id
        value: ''
      - name: retry_indicator
        value: ''
      - name: log_level
        value: INFO
  entrypoint: runnable-dag
  nodeSelector: {}
  serviceAccountName: default-editor
  templateDefaults:
    activeDeadlineSeconds: 86400
    failFast: true
    nodeSelector: {}
  templates:
    - name: stub-node-h7suho
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.09-retry.linear.main
          - stub_node
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/09-retry/original_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_PRM_param1
            value: '{{workflow.parameters.param1}}'
          - name: RUNNABLE_PRM_param2
            value: '{{workflow.parameters.param2}}'
          - name: RUNNABLE_PRM_integer
            value: '{{workflow.parameters.integer}}'
          - name: RUNNABLE_PRM_floater
            value: '{{workflow.parameters.floater}}'
          - name: RUNNABLE_PRM_stringer
            value: '{{workflow.parameters.stringer}}'
          - name: RUNNABLE_PRM_run_id
            value: '{{workflow.parameters.run_id}}'
          - name: RUNNABLE_PRM_retry_run_id
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_PRM_retry_indicator
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_PRM_log_level
            value: '{{workflow.parameters.log_level}}'
          - name: error_on_existing_run_id
            value: 'true'
          - name: argo_env
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}'
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: check-envvar-task-dax5u5
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.09-retry.linear.main
          - check_envvar_task
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/09-retry/original_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: argo_env
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}'
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: success-f0flyd
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.09-retry.linear.main
          - success
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/09-retry/original_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: argo_env
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}'
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: runnable-dag
      dag:
        tasks:
          - name: stub-node-h7suho
            template: stub-node-h7suho
            arguments:
              parameters: []
            depends: ''
          - name: check-envvar-task-dax5u5
            template: check-envvar-task-dax5u5
            arguments:
              parameters: []
            depends: stub-node-h7suho.Succeeded
          - name: success-f0flyd
            template: success-f0flyd
            arguments:
              parameters: []
            depends: check-envvar-task-dax5u5.Succeeded
      failFast: true
  volumes:
    - name: runnable
      persistentVolumeClaim:
        claimName: runnable
        readOnly: false
