apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-
  labels: {}
  namespace: enterprise-mlops
spec:
  activeDeadlineSeconds: 86400
  arguments:
    parameters:
      - name: integer
        value: 1
      - name: floater
        value: 3.14
      - name: stringer
        value: hello
      - name: run_id
      - name: retry_run_id
        value: ''
      - name: retry_indicator
        value: ''
      - name: log_level
        value: INFO
  entrypoint: runnable-dag
  nodeSelector: {}
  serviceAccountName: default-editor
  templateDefaults:
    activeDeadlineSeconds: 86400
    failFast: true
    nodeSelector: {}
  templates:
    - name: map-state-ca6xpf-fan-out
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - fan
          - '{{workflow.parameters.run_id}}'
          - map_state
          - examples.07-map.map.main
          - out
          - --log-level
          - WARNING
          - --config-file
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
          - --iter-variable
          - '{"map_variable":{},"loop_variable":[]}'
          - --mode
          - python
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_PRM_integer
            value: '{{workflow.parameters.integer}}'
          - name: RUNNABLE_PRM_floater
            value: '{{workflow.parameters.floater}}'
          - name: RUNNABLE_PRM_stringer
            value: '{{workflow.parameters.stringer}}'
          - name: RUNNABLE_PRM_run_id
            value: '{{workflow.parameters.run_id}}'
          - name: RUNNABLE_PRM_retry_run_id
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_PRM_retry_indicator
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_PRM_log_level
            value: '{{workflow.parameters.log_level}}'
          - name: error_on_existing_run_id
            value: 'true'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 1Gi
            cpu: 250m
          requests:
            memory: 1Gi
            cpu: 250m
      inputs:
        parameters: []
      outputs:
        parameters:
          - name: iterate-on
            valueFrom:
              path: /tmp/output.txt
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-ca6xpf-fan-out-ho1n'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-python-n0qj97
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map.main
          - map_state.map_variable_placeholder.execute_python
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --iter-variable
          - '{"map_variable":{"chunk":{"value":"{{inputs.parameters.chunk}}"}},"loop_variable":[]}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-notebook-uu5571
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map.main
          - map_state.map_variable_placeholder.execute_notebook
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --iter-variable
          - '{"map_variable":{"chunk":{"value":"{{inputs.parameters.chunk}}"}},"loop_variable":[]}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-shell-ocvx3t
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map.main
          - map_state.map_variable_placeholder.execute_shell
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --iter-variable
          - '{"map_variable":{"chunk":{"value":"{{inputs.parameters.chunk}}"}},"loop_variable":[]}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-read-processed-chunk-1wf8mp
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map.main
          - map_state.map_variable_placeholder.read%processed%chunk
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --iter-variable
          - '{"map_variable":{"chunk":{"value":"{{inputs.parameters.chunk}}"}},"loop_variable":[]}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-success-fs8xsn
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map.main
          - map_state.map_variable_placeholder.success
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --iter-variable
          - '{"map_variable":{"chunk":{"value":"{{inputs.parameters.chunk}}"}},"loop_variable":[]}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-ca6xpf-branch
      dag:
        tasks:
          - name: map-state-execute-python-n0qj97
            template: map-state-execute-python-n0qj97
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: ''
          - name: map-state-execute-notebook-uu5571
            template: map-state-execute-notebook-uu5571
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-python-n0qj97.Succeeded
          - name: map-state-execute-shell-ocvx3t
            template: map-state-execute-shell-ocvx3t
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-notebook-uu5571.Succeeded
          - name: map-state-read-processed-chunk-1wf8mp
            template: map-state-read-processed-chunk-1wf8mp
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-shell-ocvx3t.Succeeded
          - name: map-state-success-fs8xsn
            template: map-state-success-fs8xsn
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-read-processed-chunk-1wf8mp.Succeeded
      inputs:
        parameters:
          - name: chunk
      failFast: true
    - name: map-state-ca6xpf-fan-in
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - fan
          - '{{workflow.parameters.run_id}}'
          - map_state
          - examples.07-map.map.main
          - in
          - --log-level
          - WARNING
          - --config-file
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
          - --iter-variable
          - '{"map_variable":{},"loop_variable":[]}'
          - --mode
          - python
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 1Gi
            cpu: 250m
          requests:
            memory: 1Gi
            cpu: 250m
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-ca6xpf-fan-in-77jg'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-ca6xpf
      dag:
        tasks:
          - name: map-state-ca6xpf-fan-out
            template: map-state-ca6xpf-fan-out
            arguments:
              parameters: []
          - name: map-state-ca6xpf-branch
            template: map-state-ca6xpf-branch
            arguments:
              parameters:
                - name: chunk
                  value: '{{item}}'
            withParam: '{{tasks.map-state-ca6xpf-fan-out.outputs.parameters.iterate-on}}'
            depends: map-state-ca6xpf-fan-out.Succeeded
          - name: map-state-ca6xpf-fan-in
            template: map-state-ca6xpf-fan-in
            arguments:
              parameters: []
            depends: map-state-ca6xpf-branch.Succeeded ||
              map-state-ca6xpf-branch.Failed
      failFast: false
    - name: collect-4gl3cb
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map.main
          - collect
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --iter-variable
          - '{"map_variable":{},"loop_variable":[]}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-collect-4gl3cb-a6d5'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: success-aja72b
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map.main
          - success
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --iter-variable
          - '{"map_variable":{},"loop_variable":[]}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-success-aja72b-syqn'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: runnable-dag
      dag:
        tasks:
          - name: map-state-ca6xpf
            template: map-state-ca6xpf
            arguments:
              parameters: []
            depends: ''
          - name: collect-4gl3cb
            template: collect-4gl3cb
            arguments:
              parameters: []
            depends: map-state-ca6xpf.Succeeded
          - name: success-aja72b
            template: success-aja72b
            arguments:
              parameters: []
            depends: collect-4gl3cb.Succeeded
      failFast: true
  volumes:
    - name: runnable
      persistentVolumeClaim:
        claimName: runnable
        readOnly: false
