apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-
  labels: {}
  namespace: enterprise-mlops
spec:
  activeDeadlineSeconds: 86400
  arguments:
    parameters:
      - name: integer
        value: 1
      - name: floater
        value: 3.14
      - name: stringer
        value: hello
      - name: run_id
        value: '{{workflow.uid}}'
      - name: log_level
        value: INFO
  entrypoint: runnable-dag
  nodeSelector: {}
  serviceAccountName: default-editor
  templateDefaults:
    activeDeadlineSeconds: 86400
    failFast: true
    nodeSelector: {}
  templates:
    - name: map-state-g5mtpb-fan-out
      container:
        image: $docker_image
        command:
          - runnable
          - fan
          - '{{workflow.parameters.run_id}}'
          - map_state
          - examples.07-map.map_fail.main
          - out
          - --log-level
          - WARNING
          - --config-file
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
          - --mode
          - python
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_PRM_integer
            value: '{{workflow.parameters.integer}}'
          - name: RUNNABLE_PRM_floater
            value: '{{workflow.parameters.floater}}'
          - name: RUNNABLE_PRM_stringer
            value: '{{workflow.parameters.stringer}}'
          - name: RUNNABLE_PRM_run_id
            value: '{{workflow.parameters.run_id}}'
          - name: RUNNABLE_PRM_log_level
            value: '{{workflow.parameters.log_level}}'
          - name: error_on_existing_run_id
            value: 'true'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 1Gi
            cpu: 250m
          requests:
            memory: 1Gi
            cpu: 250m
      inputs:
        parameters: []
      outputs:
        parameters:
          - name: iterate-on
            valueFrom:
              path: /tmp/output.txt
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-python-s0eze9
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.execute_python
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: argo_env
            value: argo
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-notebook-lyxara
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.execute_notebook
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: argo_env
            value: argo
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-shell-qlg7gd
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.execute_shell
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: argo_env
            value: argo
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-read-processed-chunk-e5lg41
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.read%processed%chunk
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: argo_env
            value: argo
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-success-kcf98m
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.success
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env: []
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-g5mtpb-branch
      dag:
        tasks:
          - name: map-state-execute-python-s0eze9
            template: map-state-execute-python-s0eze9
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: ''
          - name: map-state-execute-notebook-lyxara
            template: map-state-execute-notebook-lyxara
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-python-s0eze9.Succeeded
          - name: map-state-execute-shell-qlg7gd
            template: map-state-execute-shell-qlg7gd
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-notebook-lyxara.Succeeded
          - name: map-state-read-processed-chunk-e5lg41
            template: map-state-read-processed-chunk-e5lg41
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-shell-qlg7gd.Succeeded
          - name: map-state-success-kcf98m
            template: map-state-success-kcf98m
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-read-processed-chunk-e5lg41.Succeeded
      inputs:
        parameters:
          - name: chunk
      failFast: true
    - name: map-state-g5mtpb-fan-in
      container:
        image: $docker_image
        command:
          - runnable
          - fan
          - '{{workflow.parameters.run_id}}'
          - map_state
          - examples.07-map.map_fail.main
          - in
          - --log-level
          - WARNING
          - --config-file
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
          - --mode
          - python
        imagePullPolicy: Always
        env: []
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 1Gi
            cpu: 250m
          requests:
            memory: 1Gi
            cpu: 250m
      inputs:
        parameters: []
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-g5mtpb
      dag:
        tasks:
          - name: map-state-g5mtpb-fan-out
            template: map-state-g5mtpb-fan-out
            arguments:
              parameters: []
          - name: map-state-g5mtpb-branch
            template: map-state-g5mtpb-branch
            arguments:
              parameters:
                - name: chunk
                  value: '{{item}}'
            withParam: '{{tasks.map-state-g5mtpb-fan-out.outputs.parameters.iterate-on}}'
            depends: map-state-g5mtpb-fan-out.Succeeded
          - name: map-state-g5mtpb-fan-in
            template: map-state-g5mtpb-fan-in
            arguments:
              parameters: []
            depends: map-state-g5mtpb-branch.Succeeded ||
              map-state-g5mtpb-branch.Failed
      failFast: false
    - name: collect-cgyp5k
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - collect
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: argo_env
            value: argo
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: success-0l0aiw
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - success
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env: []
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: runnable-dag
      dag:
        tasks:
          - name: map-state-g5mtpb
            template: map-state-g5mtpb
            arguments:
              parameters: []
            depends: ''
          - name: collect-cgyp5k
            template: collect-cgyp5k
            arguments:
              parameters: []
            depends: map-state-g5mtpb.Succeeded
          - name: success-0l0aiw
            template: success-0l0aiw
            arguments:
              parameters: []
            depends: collect-cgyp5k.Succeeded
      failFast: true
  volumes:
    - name: runnable
      persistentVolumeClaim:
        claimName: runnable
        readOnly: false
