apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-
  labels: {}
  namespace: enterprise-mlops
spec:
  activeDeadlineSeconds: 86400
  arguments:
    parameters:
      - name: integer
        value: 1
      - name: floater
        value: 3.14
      - name: stringer
        value: hello
      - name: run_id
      - name: retry_run_id
        value: ''
      - name: retry_indicator
        value: ''
      - name: log_level
        value: INFO
  entrypoint: runnable-dag
  nodeSelector: {}
  serviceAccountName: default-editor
  templateDefaults:
    activeDeadlineSeconds: 86400
    failFast: true
    nodeSelector: {}
  templates:
    - name: map-state-rgurd0-fan-out
      container:
        image: $docker_image
        command:
          - runnable
          - fan
          - '{{workflow.parameters.run_id}}'
          - map_state
          - examples.07-map.map_fail.main
          - out
          - --log-level
          - WARNING
          - --config-file
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
          - --mode
          - python
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_PRM_integer
            value: '{{workflow.parameters.integer}}'
          - name: RUNNABLE_PRM_floater
            value: '{{workflow.parameters.floater}}'
          - name: RUNNABLE_PRM_stringer
            value: '{{workflow.parameters.stringer}}'
          - name: RUNNABLE_PRM_run_id
            value: '{{workflow.parameters.run_id}}'
          - name: RUNNABLE_PRM_retry_run_id
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_PRM_retry_indicator
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_PRM_log_level
            value: '{{workflow.parameters.log_level}}'
          - name: error_on_existing_run_id
            value: 'true'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 1Gi
            cpu: 250m
          requests:
            memory: 1Gi
            cpu: 250m
      inputs:
        parameters: []
      outputs:
        parameters:
          - name: iterate-on
            valueFrom:
              path: /tmp/output.txt
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-rgurd0-fan-out'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-python-rs6ijf
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.execute_python
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-execute-python-rs6ijf'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-notebook-v3sow5
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.execute_notebook
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-execute-notebook-v3sow5'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-execute-shell-lnjrx7
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.execute_shell
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-execute-shell-lnjrx7'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-read-processed-chunk-wtahfu
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.read%processed%chunk
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-read-processed-chunk-wtahfu'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-success-3ye852
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - map_state.map_variable_placeholder.success
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --map-variable
          - '{"chunk": "{{inputs.parameters.chunk}}"}'
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters:
          - name: chunk
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-success-3ye852'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-rgurd0-branch
      dag:
        tasks:
          - name: map-state-execute-python-rs6ijf
            template: map-state-execute-python-rs6ijf
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: ''
          - name: map-state-execute-notebook-v3sow5
            template: map-state-execute-notebook-v3sow5
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-python-rs6ijf.Succeeded
          - name: map-state-execute-shell-lnjrx7
            template: map-state-execute-shell-lnjrx7
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-notebook-v3sow5.Succeeded
          - name: map-state-read-processed-chunk-wtahfu
            template: map-state-read-processed-chunk-wtahfu
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-execute-shell-lnjrx7.Succeeded
          - name: map-state-success-3ye852
            template: map-state-success-3ye852
            arguments:
              parameters:
                - name: chunk
                  value: '{{inputs.parameters.chunk}}'
            depends: map-state-read-processed-chunk-wtahfu.Succeeded
      inputs:
        parameters:
          - name: chunk
      failFast: true
    - name: map-state-rgurd0-fan-in
      container:
        image: $docker_image
        command:
          - runnable
          - fan
          - '{{workflow.parameters.run_id}}'
          - map_state
          - examples.07-map.map_fail.main
          - in
          - --log-level
          - WARNING
          - --config-file
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
          - --mode
          - python
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 1Gi
            cpu: 250m
          requests:
            memory: 1Gi
            cpu: 250m
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-map-state-rgurd0-fan-in'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: map-state-rgurd0
      dag:
        tasks:
          - name: map-state-rgurd0-fan-out
            template: map-state-rgurd0-fan-out
            arguments:
              parameters: []
          - name: map-state-rgurd0-branch
            template: map-state-rgurd0-branch
            arguments:
              parameters:
                - name: chunk
                  value: '{{item}}'
            withParam: '{{tasks.map-state-rgurd0-fan-out.outputs.parameters.iterate-on}}'
            depends: map-state-rgurd0-fan-out.Succeeded
          - name: map-state-rgurd0-fan-in
            template: map-state-rgurd0-fan-in
            arguments:
              parameters: []
            depends: map-state-rgurd0-branch.Succeeded ||
              map-state-rgurd0-branch.Failed
      failFast: false
    - name: collect-vqmxqt
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - collect
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-collect-vqmxqt'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: success-a5jd2d
      container:
        image: $docker_image
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.07-map.map_fail.main
          - success
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
          - --parameters-file
          - examples/common/initial_parameters.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_CODE_ID_ARGO_WORKFLOW_UID
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-success-a5jd2d'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: runnable-dag
      dag:
        tasks:
          - name: map-state-rgurd0
            template: map-state-rgurd0
            arguments:
              parameters: []
            depends: ''
          - name: collect-vqmxqt
            template: collect-vqmxqt
            arguments:
              parameters: []
            depends: map-state-rgurd0.Succeeded
          - name: success-a5jd2d
            template: success-a5jd2d
            arguments:
              parameters: []
            depends: collect-vqmxqt.Succeeded
      failFast: true
  volumes:
    - name: runnable
      persistentVolumeClaim:
        claimName: runnable
        readOnly: false
