apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-
  labels: {}
  namespace: enterprise-mlops
spec:
  activeDeadlineSeconds: 86400
  arguments:
    parameters:
      - name: run_id
      - name: retry_run_id
        value: ''
      - name: retry_indicator
        value: ''
      - name: log_level
        value: INFO
  entrypoint: runnable-dag
  nodeSelector: {}
  serviceAccountName: default-editor
  templateDefaults:
    activeDeadlineSeconds: 86400
    failFast: true
    nodeSelector: {}
  templates:
    - name: stub-node-k289qa
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.09-retry.linear.main
          - stub_node
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_PRM_run_id
            value: '{{workflow.parameters.run_id}}'
          - name: RUNNABLE_PRM_retry_run_id
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_PRM_retry_indicator
            value: '{{workflow.parameters.retry_indicator}}'
          - name: RUNNABLE_PRM_log_level
            value: '{{workflow.parameters.log_level}}'
          - name: error_on_existing_run_id
            value: 'true'
          - name: argo_env
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-stub-node-k289qa'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: check-envvar-task-etzbhy
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.09-retry.linear.main
          - check_envvar_task
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: argo_env
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-check-envvar-task-etzbhy'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: success-5let3b
      container:
        image: harbor.csis.astrazeneca.net/mlops/runnable:latest
        command:
          - runnable
          - execute-single-node
          - '{{workflow.parameters.run_id}}'
          - examples.09-retry.linear.main
          - success
          - --log-level
          - '{{workflow.parameters.log_level}}'
          - --mode
          - python
          - --config
          - examples/configs/argo-config.yaml
        imagePullPolicy: Always
        env:
          - name: RUNNABLE_RETRY_RUN_ID
            value: '{{workflow.parameters.retry_run_id}}'
          - name: RUNNABLE_RETRY_INDICATOR
            value: '{{workflow.parameters.retry_indicator}}'
          - name: argo_env
            value: '{{workflow.uid}}'
        volumeMounts:
          - mountPath: /tmp
            name: runnable
            readOnly: false
        resources:
          limits:
            memory: 4Gi
            cpu: '2'
          requests:
            memory: 4Gi
            cpu: '2'
      inputs:
        parameters: []
      memoize:
        key: '{{workflow.parameters.run_id}}-success-5let3b'
        cache:
          configMap:
            name: kf-configmap
            key: cache
      activeDeadlineSeconds: 86400
      nodeSelector: {}
      volumes:
        - name: runnable
          persistentVolumeClaim:
            claimName: runnable
            readOnly: false
    - name: runnable-dag
      dag:
        tasks:
          - name: stub-node-k289qa
            template: stub-node-k289qa
            arguments:
              parameters: []
            depends: ''
          - name: check-envvar-task-etzbhy
            template: check-envvar-task-etzbhy
            arguments:
              parameters: []
            depends: stub-node-k289qa.Succeeded
          - name: success-5let3b
            template: success-5let3b
            arguments:
              parameters: []
            depends: check-envvar-task-etzbhy.Succeeded
      failFast: true
  volumes:
    - name: runnable
      persistentVolumeClaim:
        claimName: runnable
        readOnly: false
