dag:
  description: |
    This is a simple pipeline that does 3 steps in sequence.

    step 1 >> step 2 >> success

    Log levels:
      runnable log level is different from your application log level. By default, it is set to WARNING but you can
      control it by using --log-level while calling application.

    To view only your application logs, you can execute this pipeline with:
      runnable execute logging.yaml --log-level ERROR

  start_at: step 1
  steps:
    step 1:
      type: task
      command_type: python
      command: examples.functions.return_parameter
      next: step 2
    step 2:
      type: task
      command_type: python
      command: examples.functions.display_parameter
      next: success
    success:
      type: success
    fail:
      type: fail
