pipeline-executor:
  type: "argo" # (1)
  config:
    pvc_for_runnable: runnable
    argoWorkflow:
      metadata:
        generateName: "argo-" # (2)
        namespace: enterprise-mlops
      spec:
        serviceAccountName: "default-editor"
        templateDefaults:
          image: harbor.csis.astrazeneca.net/mlops/runnable:latest # (2)


run-log-store: # (4)
  type: chunked-fs
  # config:
  #   log_folder: /mnt/run_log_store
