executor:
  type: argo
  config:
    image: $argo_docker_image
    max_workflow_duration_in_seconds: 86400 # Apply to spec
    node_selector:
    parallelism: 1 #apply to spec
    service_account_name1: pipeline-runner
    resources:
      limits:
        memory: 140Mi
        cpu: 100m
      requests:
       memory: 100Mi
       cpu: 10m
    retry_strategy:
      limit: 0 #int
      retryPolicy: "always"
      backoff:
        duration:
        factor:
        max_duration:
    max_step_duration_in_seconds: 60 # apply to templateDefaults
    tolerations: # apply to spec
    image_pull_policy: "" # apply to template
    persistent_volumes: # (3)
      - name: runnable-volume
        mount_path: /mnt

    # overrides:
    #   override:
    #     tolerations: # template
    #     image: # container
    #     max_step_duration: # template
    #     step_timeout: #template
    #     nodeSelector: #template
    #     parallelism: # this need to applied for map
    #     resources: # container
    #     imagePullPolicy: #container
    #     retryStrategy: # template

run_log_store: # (5)
  type: chunked-fs
  config:
    log_folder: /mnt/run_log_store # (6)

catalog: # (5)
  type: file-system
  config:
    catalog_location: /mnt/catalog # (6)
