pipeline-executor:
  type: "argo" # (1)
  config:
    pvc_for_runnable: runnable
    defaults:
      image: harbor.csis.astrazeneca.net/mlops/runnable:latest # (2)
    overrides:
      cpu-machine:
        # image: harbor.csis.astrazeneca.net/mlops/runnable:latest # (2)
        tolerations:
        - effect: "NoSchedule"
          key: "as_m5_4xlarge_ns"
          operator: "Equal"
          value: "true"
        - effect: "NoExecute"
          key: "as_m5_4xlarge_ne"
          operator: "Equal"
          value: "true"
        resources:
          limits:
            cpu: "4"
            memory: "16Gi"
          requests:
            cpu: "4"
            memory: "16Gi"
    argoWorkflow:
      metadata:
        generateName: "argo-" # (2)
        namespace: enterprise-mlops
      spec:
        serviceAccountName: "default-editor"


run-log-store: # (4)
  type: chunked-fs
  # config:
  #   log_folder: /mnt/run_log_store
