catalog:
  type: file-system # (1)

run-log-store:
  type: file-system # (1)

pipeline-executor:
  type: mocked
  config:
    patches:
      chunk files:
        command: examples.concepts.map.chunk_files
