name: docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: "Set up Python"
        run: uv python install
      - run: |
          uv sync --only-group docs
          uv run mkdocs gh-deploy --force
