on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "examples/**"
      - "mkdocs.yml"
    branches:
      - "main"

jobs:
  PRCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: python -m pip install poetry
      - run: |
          # Download the binary
          curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.5.4/argo-linux-amd64.gz

          # Unzip
          gunzip argo-linux-amd64.gz

          # Make binary executable
          chmod +x argo-linux-amd64

          # Move binary to path
          mv ./argo-linux-amd64 /usr/local/bin/argo

          # Test installation
          argo version

      - run: |
          python -m poetry install
          poetry run tox
