on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "examples/**"
      - "mkdocs.yml"
    branches:
      - "main"
  workflow_dispatch:
  workflow_call:

jobs:
  PRCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: python -m pip install poetry
      - run: |
          # Download the binary
          curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.5.4/argo-linux-amd64.gz

          # Unzip
          gunzip argo-linux-amd64.gz

          # Make binary executable
          chmod +x argo-linux-amd64

          # Move binary to path
          mv ./argo-linux-amd64 /usr/local/bin/argo

          # Test installation
          argo version

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run lint
        # For example, using `flake8`
        run: uvx ruff format

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest -m "not container"

      - name: mypy
        run: uv run mypy runnable extensions
