import logging
from pathlib import Path

from magnus.extensions.run_log_store.file_system import integration


def test_local_compute_throws_warning(mocker, caplog):
    mock_executor = mocker.MagicMock()
    mock_executor._is_parallel_execution.return_value = True

    test_integration = integration.LocalComputeFileSystemRunLogStore(executor=mock_executor, integration_service="test")

    with caplog.at_level(logging.WARNING, logger="magnus"):
        test_integration.validate()

    assert "Run log generated by file-system run log store are not thread safe." in caplog.text


def test_local_container_validate_throws_warning(mocker, caplog):
    mock_executor = mocker.MagicMock()
    mock_executor._is_parallel_execution.return_value = True

    test_integration = integration.LocalContainerComputeFileSystemRunLogstore(
        executor=mock_executor, integration_service="test"
    )

    with caplog.at_level(logging.WARNING, logger="magnus"):
        test_integration.validate()

    assert "Run log generated by file-system run log store are not thread safe." in caplog.text


def test_container_configure_for_traversal_populates_volumes(mocker, monkeypatch):
    mock_local_container = mocker.MagicMock()
    monkeypatch.setattr(integration, "LocalContainerExecutor", mock_local_container)

    mock_executor = mocker.MagicMock()
    mock_executor._volumes = {}
    mock_executor._container_log_location = "this_location"

    mock_fs_run_log_store = mocker.MagicMock()
    mock_fs_run_log_store.log_folder_name = "run_log_location"

    test_integration = integration.LocalContainerComputeFileSystemRunLogstore(mock_executor, mock_fs_run_log_store)
    test_integration.configure_for_traversal()

    assert mock_executor._volumes == {str(Path("run_log_location").resolve()): {"bind": "this_location", "mode": "rw"}}


def test_configure_for_execution_assigns_catalog_location_within_container(mocker, monkeypatch):
    mock_local_container = mocker.MagicMock()
    monkeypatch.setattr(integration, "LocalContainerExecutor", mock_local_container)

    mock_executor = mocker.MagicMock()
    mock_executor._container_log_location = "this_location"

    mock_fs_run_log_store = mocker.MagicMock()

    test_integration = integration.LocalContainerComputeFileSystemRunLogstore(mock_executor, mock_fs_run_log_store)
    test_integration.configure_for_execution()

    assert mock_fs_run_log_store.log_folder == "this_location"
